sonata_core:
    flashmessage:
        warning:
            types:
                - { type: sonata_warning, domain: SonataAdminBundle }
    form:
        mapping:
            enabled: false
sonata_user:
    class:
        user:               App\Application\Sonata\UserBundle\Entity\User
        group:              App\Application\Sonata\UserBundle\Entity\Group
