sonata_admin:
    title: 'Mon Auto Ecole'
   
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
   
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        
    