<?php

namespace App\Application\Sonata\UserBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use Sonata\AdminBundle\Util\ObjectAclManipulatorInterface;
use Sonata\AdminBundle\Admin\AdminInterface;
use Sonata\AdminBundle\Exception\ModelManagerException;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Security\Acl\Domain\UserSecurityIdentity;
//use FOS\UserBundle\Model\User as BaseUser;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Sonata\UserBundle\Model\UserInterface;
/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class User extends BaseUser 
{
   /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function getUsername()
    {
        return $this->username;
    }
    public function getId()
    {
        return $this->id;
    }
    
  
    public function getGenderC(){
       if ($this->getGender()=='u'){
           return "Unknown";
       }elseif($this->getGender()==('f')){
           return "Female";
       }else {
           return "Male";
       }
    }
    public static function getGenderList()
{
    return array(
        UserInterface::GENDER_UNKNOWN => 'u',
        UserInterface::GENDER_FEMALE  => 'f',
        UserInterface::GENDER_MALE    => 'm',
    );
}

   public $firstname;

   
   public function setFirstName( $firstname) {
        $this->firstname= $firstname;

        return $this;
    }
    /**
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->firstname;
    }
    
    public $lastname;

   
   public function setLastName( $lastname) {
        $this->lastname= $lastname;

        return $this;
    }
    public function getLastName()
    {
        return $this->lastname;
    }

   

}
